<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="14" total="16" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="6914" started-at="2018-12-25T22:26:00Z" finished-at="2018-12-25T22:26:07Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="6914" started-at="2018-12-25T22:26:00Z" finished-at="2018-12-25T22:26:07Z">
      <class name="com.xyz.base.TestCaseBase">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.xyz.base.TestCaseBase@289d1c02]" name="setup" is-config="true" duration-ms="14694" started-at="2018-12-26T03:55:45Z" finished-at="2018-12-26T03:56:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.xyz.base.TestCaseBase@289d1c02]" name="tearDown" is-config="true" duration-ms="870" started-at="2018-12-26T03:56:08Z" finished-at="2018-12-26T03:56:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.xyz.base.TestCaseBase -->
      <class name="com.xyz.testcases.TestCaseBankManagerLogin">
        <test-method status="PASS" signature="TestCaseBankManagerLogin()[pri:0, instance:com.xyz.testcases.TestCaseBankManagerLogin@22eeefeb]" name="TestCaseBankManagerLogin" duration-ms="3129" started-at="2018-12-26T03:56:00Z" finished-at="2018-12-26T03:56:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCaseBankManagerLogin -->
      </class> <!-- com.xyz.testcases.TestCaseBankManagerLogin -->
      <class name="com.xyz.testcases.TestCaseAddCustomerBankManager">
        <test-method status="FAIL" signature="testCaseAddCustomerBankManager()[pri:0, instance:com.xyz.testcases.TestCaseAddCustomerBankManager@17d0685f]" name="testCaseAddCustomerBankManager" duration-ms="3752" started-at="2018-12-26T03:56:03Z" finished-at="2018-12-26T03:56:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [a] but found [Customer added successfully with customer id :6]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [a] but found [Customer added successfully with customer id :6]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.xyz.testcases.TestCaseAddCustomerBankManager.testCaseAddCustomerBankManager(TestCaseAddCustomerBankManager.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseAddCustomerBankManager -->
      </class> <!-- com.xyz.testcases.TestCaseAddCustomerBankManager -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
